Repository Chemaclass/create-pr, pull requests merged in 2024-09, with the labels that each got.

#15 Fix format pr body with branch with numbers
  CHANGELOG.md
  create-pr.sh
  src/pr_format.sh
  tests/format_pr_body_test.sh
  tests/format_title_test.sh
  tests/ticket_key_test.sh
  tests/ticket_number_test.sh
Labels: bug

#17 Add default BACKGROUND placeholder
  .editorconfig
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  create-pr.sh
  src/pr_format.sh
  tests/format_pr_body_test.sh
Labels: enhancement

#18 Enable placeholders inside comments
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  src/pr_format.sh
  tests/format_pr_body_test.sh
Labels: enhancement

#19 Labels mapping
  .env.example
  create-pr.sh
  src/pr_format.sh
  tests/find_default_label_test.sh
  tests/get_default_label_test.sh
Labels: enhancement

#20 Add version
  create-pr.sh
  src/console_header.sh
Labels: enhancement

#29 Support ticket link with number
  .env.example
  CHANGELOG.md
  Makefile
  src/pr_format.sh
  tests/format_pr_body_test.sh
Labels: enhancement

#31 Remove ticket number from PR title
  CHANGELOG.md
  src/pr_format.sh
  tests/format_title_test.sh
Labels: enhancement

#33 Add closes to pr body link when no key
  src/pr_format.sh
  tests/format_pr_body_test.sh
Labels: enhancement

#34 Ticket prefix text
  .env.example
  .env.tests
  CHANGELOG.md
  Makefile
  create-pr.sh
  src/check_os.sh
  src/console_header.sh
  src/env_configuration.sh
  src/main.sh
  src/pr_body.sh
  src/pr_format.sh
  src/pr_label.sh
  src/pr_ticket.sh
  src/pr_title.sh
  src/validation.sh
  tests/e2e/create-pr_test.sh
  tests/e2e/snapshots/create_pr_test_sh.test_success.snapshot
  tests/format_pr_body_test.sh
  tests/get_label_test.sh
  tests/ticket_key_test.sh
  tests/ticket_number_test.sh
  tests/unit/pr_body_test.sh
  tests/unit/pr_label_test.sh
  tests/unit/pr_ticket_key_test.sh
  tests/unit/pr_ticket_number_test.sh
  tests/unit/pr_title_test.sh
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_background_without_link.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_with_PR_TICKET_LINK_PREFIX.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_with_branch_with_numbers_and_prefix.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_with_branch_with_numbers_no_prefix.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_with_pr_ticket_prefix_text.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_without_ticket_key.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_without_ticket_link_prefix.snapshot
  tests/unit/snapshots/pr_body_test_sh.test_pr_body_link_without_ticket_number.snapshot
Labels: enhancement

#35 Add option title
  CHANGELOG.md
  create-pr.sh
  src/console_header.sh
  src/helpers.sh
  tests/unit/helpers_test.sh
Labels: enhancement

#36 Enable custom pr title using placeholders
  .env.example
  .env.tests
  CHANGELOG.md
  src/env_configuration.sh
  src/pr_title.sh
  tests/e2e/create-pr_test.sh
  tests/unit/pr_title_test.sh
Labels: enhancement

#37 Improve readme
  README.md
Labels: documentation

#38 Rename template dir to path
  .env.example
  CHANGELOG.md
  README.md
  src/env_configuration.sh
  tests/e2e/create-pr_test.sh
Labels: enhancement

#42 Update readme
  README.md
Labels: documentation

#39 Add gitlab support
  .env.tests
  CHANGELOG.md
  Makefile
  README.md
  create-pr.sh
  src/env_configuration.sh
  src/main.sh
  src/pr_body.sh
  src/validation.sh
  tests/e2e/create-pr_test.sh
  tests/e2e/snapshots/create_pr_test_sh.test_debug_success.snapshot
  tests/e2e/snapshots/create_pr_test_sh.test_success.snapshot
Labels: enhancement

#48 Rename entry point
  .env.example
  .github/CONTRIBUTING.md
  CHANGELOG.md
  README.md
  build.sh
  create-pr
  src/console_header.sh
  tests/e2e/create-pr_test.sh
  tests/e2e/snapshots/create_pr_test_sh.test_script_with_debug.snapshot
Labels: enhancement

#49 Improve dry run
  CHANGELOG.md
  create-pr
  tests/e2e/create-pr_test.sh
  tests/e2e/snapshots/create_pr_test_sh.test_script_with_debug.snapshot
  tests/e2e/snapshots/create_pr_test_sh.test_script_with_dry_run.snapshot
Labels: enhancement

#54 Improve validation and other renamings
  README.md
  create-pr
  src/env_configuration.sh
  src/main.sh
  src/validate.sh
  tests/e2e/create-pr_test.sh
  tests/e2e/snapshots/create_pr_test_sh.test_script_with_dry_run.snapshot
  tests/e2e/snapshots/create_pr_test_sh.test_script_with_dry_run_and_extra_args.snapshot
Labels: enhancement
